# JLAM CONSOLIDATED INFRASTRUCTURE
# Base: EXACT CURRENT PRODUCTION CONFIGURATION (Working on 51.158.190.109)
# Created by: ELITE DEVOPS MASTER
# Date: 2025-08-26
# Status: PRODUCTION MIRROR - Ready for incremental enhancements

services:
  traefik:
    image: traefik:v3.0
    container_name: jlam-traefik
    restart: unless-stopped
    ports:
      - "8082:80"   # Local port 8082 (avoiding conflicts)
      - "8443:443"  # Local port 8443 for SSL
      - "9080:8080" # Dashboard on 9080
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=INFO"
      # ODIN BLESSED: Health check endpoint for monitoring
      - "--ping=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config/ssl:/etc/ssl/jlam:ro"
      - "./config/traefik:/etc/traefik/dynamic:ro"
    networks:
      - jlam-network
    # ODIN BLESSED: Comprehensive health monitoring
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # ODIN BLESSED: Resource limits for predictable scaling
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
      # ODIN PATTERN: Service discovery and restart policies
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    # ODIN BLESSED: Enterprise service discovery labels
    labels:
      - "jlam.service.name=traefik"
      - "jlam.service.type=load-balancer"
      - "jlam.service.tier=infrastructure"
      - "jlam.service.version=3.0.4"
      - "jlam.monitoring.enabled=true"
      - "jlam.monitoring.port=8080"
      - "jlam.monitoring.path=/ping"
      - "jlam.scaling.min=1"
      - "jlam.scaling.max=1"
      - "odin.pattern=enterprise-gateway"
  
  nginx:
    image: nginx:alpine
    container_name: jlam-web
    restart: unless-stopped
    volumes:
      - "./app:/usr/share/nginx/html:ro"
      - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - jlam-network
    # ODIN BLESSED: Enterprise-grade health monitoring with optimized endpoint
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # ODIN BLESSED: Resource limits for predictable performance
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.3'
        reservations:
          memory: 32M
          cpus: '0.1'
      # ODIN PATTERN: Service discovery and restart policies  
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 120s
    labels:
      - "traefik.enable=true"
      # ODIN BLESSED: HTTP router with security headers
      - "traefik.http.routers.web.rule=Host(`localhost`) || Host(`jlam.local`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web.middlewares=security-headers@file,rate-limit@file"
      # ODIN BLESSED: HTTPS router with enhanced security  
      - "traefik.http.routers.web-secure.rule=Host(`localhost`) || Host(`jlam.local`)"  
      - "traefik.http.routers.web-secure.entrypoints=websecure"
      - "traefik.http.routers.web-secure.tls=true"
      - "traefik.http.routers.web-secure.middlewares=security-headers@file,rate-limit@file"
      # ODIN PATTERN: Service configuration
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.http.services.nginx.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.nginx.loadbalancer.healthcheck.interval=30s"
      # ODIN BLESSED: Enterprise service discovery labels
      - "jlam.service.name=nginx"
      - "jlam.service.type=web-server"
      - "jlam.service.tier=frontend"
      - "jlam.service.version=alpine"
      - "jlam.monitoring.enabled=true"
      - "jlam.monitoring.port=80"
      - "jlam.monitoring.path=/health"
      - "jlam.scaling.min=1"
      - "jlam.scaling.max=3"
      - "odin.pattern=enterprise-frontend"

networks:
  jlam-network:
    driver: bridge